name: CI

on: push

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn lint

  build:
    name: Build
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          yarn
          yarn build
      - name: package
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          zip -r vivify-macos.zip bin/macos/*
          zip -r vivify-linux.zip bin/linux/*
      - name: release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: vivify-*.zip
