name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn lint

  build-linux:
    name: Build Linux
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: build
        run: |
          yarn
          make linux
      - name: package
        run: |
          cd build/linux
          zip -r vivify-linux.zip *
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vivify-linux
          path: build/linux/vivify-linux.zip

  build-macos:
    name: Build MacOS
    needs: [lint]
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          yarn
          make macos
      - name: package
        run: |
          cd build/macos
          zip -r vivify-macos.zip *
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vivify-macos
          path: build/macos/vivify-macos.zip

  release:
    name: Release
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: download linux artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v4
        with:
          name: vivify-linux
          path: .
      - name: download macos artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v4
        with:
          name: vivify-macos
          path: .
      - name: release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: vivify-*.zip
