name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn lint

  build-linux:
    name: Build Linux
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: build
        run: |
          yarn
          make linux
      - name: package
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          zip -r vivify-linux.zip bin/linux/*
      - name: upload artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: vivify-linux
          path: vivify-linux.zip

  build-macos:
    name: Build MacOS
    needs: [lint]
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          yarn
          make macos
      - name: package
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          zip -r vivify-macos.zip bin/macos/*
      - name: upload artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: vivify-macos
          path: vivify-macos.zip

  release:
    name: Release
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: download linux artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v3
        with:
          name: vivify-linux
          path: .
      - name: download macos artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v3
        with:
          name: vivify-macos
          path: .
      - name: release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: vivify-*.zip
